### ISSUE TITLE
idea for fixing mojang bug / leaf decay.

### ISSUE THREAD

**Issue by Khikki** [Roadhog360/Et-Futurum#13]
Hi, it's me again, I promise that this is the last post not related to Et Futurum directly, today I want to talk about the problem of minecraft 1.7.10 itself.

From the old versions, there is a bug that when generating the foliage of large trees begins to decaying.

https://youtu.be/Y5mqmsUgW-4
https://bugs.mojang.com/browse/MC-95657
https://bugs.mojang.com/browse/MC-1809
https://bugs.mojang.com/browse/MC-98557

From what I have heard, the radius that leaves can survive near a log has been increased to 6.
In subsequent versions, this problem was resolved, take a look if you have any free time.

PostScriptum: Sorry if I'm annoying you. т^т

**Comment by Roadhog360** [comment]
Enhancement requests are not a problem. Post as many issues as you feel the need to! I'm unsure if doing this is possible within Forge's limitations but I can look into it.

Meanwhile I think a good target for your suggestion would also be jss2a98aj's BugTorch. https://github.com/jss2a98aj/BugTorch

**Comment by Roadhog360** [comment]
I've decided to make ideas like this use the "Discussion" tab. On top head over there and post this under the "Ideas" category there!
