### ISSUE TITLE
A "limited" edition of the 1.17 caves and ore gen?

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#21]
Title says all. Et Futurum could have a somewhat watered down version of 1.17's caves and ore generation. Even though we wouldn't have an increased height above or below the world, it'd be kind of cool to see bigger caves.

Besides, no cave generation mods exist in 1.7.10, and this mod would be perfect for it since bits of 1.17 are added.

**Comment by Roadhog360** [comment]
For now I don't think I will be developing this, will be reopened if I reconsider the idea

**Comment by MagmaBro123** [comment]
Well, keeping it open may help since you'll forget it probably.
