### ISSUE TITLE
1.17's new particles/sounds?

### ISSUE THREAD

**Issue by MagmaBro123** [Roadhog360/Et-Futurum#28]
There's quite a few missing sounds/particles. And the missing lightning rod.

Copper being waxed, copper being un-oxidized via an axe, etc.

**Comment by Roadhog360** [comment]
Copper being oxidized and waxed doesn't make a sound in vanilla. The lightning rod is already planned.

**Comment by MagmaBro123** [comment]
Actually, it does make sounds. Try doing it on your end.

**Comment by Roadhog360** [comment]
Did they change it and not log the change? Because when I tried it when the mechanic was first added there was no sound

**Comment by MagmaBro123** [comment]
/playsound minecraft:item.honeycomb.wax_on hostile @p

![2021-04-11_12 00 22](https://user-images.githubusercontent.com/51277766/114315741-1f4f9780-9ab5-11eb-943e-c375e719d079.png)

Copper also has its own sounds as well.

/playsound minecraft:block.copper.break hostile @p
/playsound minecraft:block.copper.fall hostile @p
/playsound minecraft:block.copper.hit hostile @p
/playsound minecraft:block.copper.place hostile @p
/playsound minecraft:block.copper.step hostile @p

And as shown in the screenshot, orange particles occur when waxing it.

White ones also occur when un-waxing it as well. his also has its own sound.

![2021-04-11_12 03 13](https://user-images.githubusercontent.com/51277766/114315831-8bca9680-9ab5-11eb-9f64-68965383f7a0.png)

/playsound minecraft:item.axe.scrape hostile @p

**Comment by Roadhog360** [comment]
I never play with sounds off. Looks like they added this in 14a and didn't log it anywhere.

**Comment by MagmaBro123** [comment]
Ah, mk. Well, at least you know now.

**Comment by Roadhog360** [comment]
Will  reopen one I confirm it btw

**Comment by MagmaBro123** [comment]
> Will reopen once I confirm it btw

So uh, yay or nay?

**Comment by Roadhog360** [comment]
Confirmed, the sound caption is also "Wax on" and "Wax off" which is an absolutely amazing, lmao

**Comment by DarianLStephens** [comment]
Speaking of sounds, any chance you could add the Enchanting sounds to the Enchantment Table?
ASMC _sort of_ adds it to the vanilla one, but it isn't perfect, and doesn't work for the Et Futurum one.

**Comment by Roadhog360** [comment]
Yeah, that's planned too, I'm actually going to add more sounds in the next update.

**Comment by Roadhog360** [comment]
Oops I accidentally clicked close

**Comment by MagmaBro123** [comment]
@Roadhog360 Beacons have sounds too.

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Improvements" category and post your idea there so it's not mixed in with the issues tab.
