### ISSUE TITLE
Wither Skeletons getting withered by wither roses 

### ISSUE THREAD

**Issue by tyrael93** [Roadhog360/Et-Futurum#29]
I know that in 1.7 Wither Skeletons and regular Skeletons are the same entity and that the split only happened later on, but ever since the addition of wither roses, wither skeletons got a wither immunity and can pass through wither roses unharmed and even spawn on them. This also lets you create quite easy wither skeleton farms just by placing large amounts of wither roses.

Sadly Wither Skeletons still get damaged by EtFuturum wither roses and often die to them in the soulsand valley, Could you be interested in backporting this feature in your mod? You could run a call for getSkeletonType() on the skeleton entity instance and give them wither immunity if it's a wither skeleton.

Thanks in advance!

**Comment by Roadhog360** [comment]
I tested this in 1.16, the wiki is wrong and the roses still damage wither skeletons.

**Comment by tyrael93** [comment]
I uh-  took the time to test this myself too and yeah, they don't actually get hurt by wither roses.

I've also found additional proof that they don't, in the form of several videos with millions of views, which I will post here as a gesture of good will.

https://www.youtube.com/watch?v=HJYqVwmAbxY
https://www.youtube.com/watch?v=le_tTlKEbyw

These videos are from minecraft 1.16.

I understand this might be a mistake, please be mindful before closing someone's issues. I am certain this is just a misunderstanding. Since I cannot re-open this issue, I am going to make a new one. Thank you for your understanding of the situation.
![wither1](https://user-images.githubusercontent.com/5557920/114303411-4a92b080-9ace-11eb-8175-54a3fb815154.png)
![wither 2](https://user-images.githubusercontent.com/5557920/114303412-4bc3dd80-9ace-11eb-9017-12aec2161a1e.png)

**Comment by Roadhog360** [comment]
Will investigate

**Comment by Roadhog360** [comment]
Confirmed. I don't know why they took damage last time, but I do apologise for the misunderstanding. I'm intrigued at what caused them to take damage before and I might try to get that to happen again so I can put a bug report on the Mojira website

**Comment by Roadhog360** [comment]
![2021-05-14_14 43 47](https://user-images.githubusercontent.com/11903511/118314952-dc714d00-b4c2-11eb-9486-795ffbb70a11.png)
Fix pending release
