### ISSUE TITLE
Items are static variables accessed through reflection. This might cause Issues.

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum#33]
Item registration is done whenever they are accessed first, which when using Reflection (and only reflection) to access them will cause weird Issues like them being null when you try to register them.

I often have Issues with static variables being rather finicky with their order of execution, and adding Reflection ontop of that will just destabilize the whole thing. I am surprised the Copper Ingot was registered at all.

https://github.com/jss2a98aj/Et-Futurum/blob/92207474c1c5e177a73da907daeeedec11126beb/src/main/java/ganymedes01/etfuturum/ModItems.java#L101-L114

I dont exactly know what is wrong and how to fix this, but this code looks rather "sus" to me when it comes to my error prediction sense. XD

All my own testing when trying to add Compat came up with is "Copper Ingot does not exist in PreInit, while everything else in Et Futurum does", while also "Copper Ingot exists when I'M in Init". So this cant just be a Mod sorting Issue (I load after pretty much everything).

And the Signs which are initialized in a static {} block are very likely to be messed up, I had Issues with that a few years ago with my own static-based Code, and needed to make a function that ensures order of operations being correct.

**Comment by Roadhog360** [comment]
Is there a better solution to getting a list of the items and blocks variables?

**Comment by GregoriusT** [comment]
Initializing the Variables in preInit instead of statically would be a solution. I know it splits the whole thing up into 2 places to update Code but this would be the easiest.

Another Solution would be using the Constructor of your Item and Block Class to add the Item/Block into a HashMap<String, Item> or a HashMap<String, Block> once the Item is constructed statically. Then call some random thing on the ModItems/ModBlocks List to make sure the Class is fully loaded, afterwards iterate over both HashMaps to register all Items and Blocks at the same time in preInit. More complicated but you can keep the "one place to add em all" approach that both of us seem to like. XD

**Comment by Roadhog360** [comment]
I've decided to separate enhancements from issues, use the discussions tab on the top and ask there, you can use the "Improvements" category and post your idea there so it's not mixed in with the issues tab.

However that won't be necessary as I've pushed a solution to the repo already

**Comment by GregoriusT** [comment]
Something I wanted to mention with our fix is, that Et Futurum Items and Blocks in NEI are now actually sorted and not completely random!
