### ISSUE TITLE
Why do I have 4 Arms in my Player Model now?

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum#37]
I guess the 4 Arms thing also extends to Legs, and is caused by rendering both, the default Steve and the selected Steve/Alex Variant of the Skin at the same time.

This is only really visible when having the empty Hand out in first person, or when moving the Camera to inside of the Skin.

https://forum.mechaenetia.com/uploads/default/optimized/2X/a/aebd42bd2f4eb7fd3f88bb4fe0a1270e649fb154_2_690x387.png

**Comment by Roadhog360** [comment]
What other mods are installed?

**Comment by Roadhog360** [comment]
I can't reproduce this and I have all of those except baubles and gregtech in my workspace
