### ISSUE TITLE
enableTileReplacement=false de-transforms blocks

### ISSUE THREAD

**Issue by AstroTibs** [Roadhog360/Et-Futurum#53]
Since updating to EF 2.1.3, I noticed on my server that suddenly my Brewing Stands were the 1.7 version.
Placing both vanilla and EFR versions of Enchanting Table, Brewing Stand, and Beacon resulted in the 1.7 version. I don't know how to tell the difference between anvils.

My enableTileReplacement setting has been **false** because I was worried about performance issues.
I suspect that setting this to "false" does the same thing as "true" except automatically converting to 1.7 versions instead of 1.8.

When rolling back to v2.0.2, everything works as expected.
When set to **true**, enableTileReplacement works as expected.

I'll leave enableTileReplacement as true until this is fixed and I experience performance issues.

**Comment by Roadhog360** [comment]
Set it to true. EnableTileReplacement has had its performance fixed, false is now used to easily convert the tiles back to their vanilla versions.

In the future I want to integrate some of the changed mechanics into the base blocks using Forge's tile replacement system so I also added this option as future-proofing for whenever I wanted to do that.

**Comment by Roadhog360** [comment]
Will add an option to restore the old behavior
