### ISSUE TITLE
Some sort of sound-related crash

### ISSUE THREAD

**Issue by DarianLStephens** [Roadhog360/Et-Futurum#54]
I don't know exactly what's going on, but every once in a while, I'll get this crash:
[https://pastebin.com/smL7115T](https://pastebin.com/smL7115T)
It only happens if I enable Et Futurum's sound options; similar ones from ASMC seem fine.

This happens particularly often when fighting a shadow clone with Dragon Block C.

**Comment by Roadhog360** [comment]
I've made an attempted fix for this, when 2.2.0 comes out let me know if it's not fixed and I'll re-do this issue

**Comment by Roadhog360** [comment]
Good?

**Comment by DarianLStephens** [comment]
Well, I just gave it a try with Et Futurum's sound settings re-enabled, and no crashes after 5 battles with the shadow clones, which is a good sign.
