### ISSUE TITLE
[Suggestion] Dimension config for generation

### ISSUE THREAD

**Issue by DarianLStephens** [Roadhog360/Et-Futurum#62]
With certain dimensions, Deepslate doesn't generate, even though it definitely should.
An example is Witchery's Spirit World, which is supposed to be a near-exact replica of the Overworld.

Interestingly, Tuff still generates at these depths.

**Comment by DarianLStephens** [comment]
A comparison:
Overworld:
![2021-07-12_01 38 53](https://user-images.githubusercontent.com/15375876/125201321-f4dac980-e2b1-11eb-9050-e7d2e90c31e5.png)

Spirit World:
![2021-07-12_01 38 56](https://user-images.githubusercontent.com/15375876/125201327-f7d5ba00-e2b1-11eb-84b1-de86ad497122.png)

Note the Tuff behind the lava in both images.

**Comment by Roadhog360** [comment]
Suggestions belong in the discussions tab.

Also deepslate currently only generates in the overworld, this will be changed in the future.

**Comment by GregoriusT** [comment]
Some clarification, Deepslate will (then) generate in Blobs anywhere but the Overworld, since Dimensions like Twilight Forest are not "tall" enough for using the Deepslate Height for example.
