### ISSUE TITLE
[Suggestion] Option to disable Ocean Monument generation specifically

### ISSUE THREAD

**Issue by DarianLStephens** [Roadhog360/Et-Futurum#63]
Currently, it appears that the only options available are to completely disable everything to do with Prismarine, including Et Futurum's block and temple generation.
However, Village Names has an option to use Et Futurum's Prismarine in generation.
This is unfortunately useless given that we can only have both Et Futurum's Prismarine and temple generation, not one or the other, leading to overlapping temples, or single-prefab temples from Et Futurum, which also don't spawn Village Names' Guardians.

Example:
![2021-07-12_02 25 49](https://user-images.githubusercontent.com/15375876/125202785-80575900-e2b8-11eb-9d93-d28caead0668.png)

**Comment by Roadhog360** [comment]
Suggestions belong in the discussion tabs. Also this is already an option.
